### ISSUE TITLE
S3 bucket endpoint configuration

### ISSUE THREAD

**Issue by Marcuzz** [weareferal/craft-remote-sync#19]
Hi,

Could you look into adding a configuration option for what endpoint to use for S3? We use DigitalOcean Spaces which is 100% S3 API compatible and it would work out of the box if we could specify a custom endpoint :)

**Comment by timmyomahony** [comment]
Interesting. I recently added some more providers to `craft-remote-backup` (Backblaze, Google Drive, Dropbox) so I'll be porting that over here as soon as I can. With that I could easily add Digital Ocean Spaces

**Comment by Marcuzz** [comment]
Awesome 👍 that'd be good. Thanks!

**Comment by timmyomahony** [comment]
This should be added in `1.3.1`:

https://github.com/weareferal/craft-remote-sync/releases/tag/1.3.1

Sync now supports:

- AWS
- Dropbox
- Digital Ocean
- Backblaze
- Google Drive
