### ISSUE TITLE
How to debug access issues

### ISSUE THREAD

**Issue by indrek-k** [weareferal/craft-remote-sync#25]
Hi there!

Problem:
```
./craft.bat remote-sync/database/list
Error: AWS Error (Check credentials)
```

However, when attempting to connect to AWS using the exact same credentials via AWS CLI, I can connect and for example, list objects in the specified bucket.

How can I debug this issue?

**Comment by timmyomahony** [comment]
Hmmm, that's strange. You should be able to see more details in the `storage/logs/console.log` file (or the `storage/logs/web.log` file if you are using the Control Panel interface). 

The plugin is using the PHP SDK behind the scenes (not the AWS CLI) so I wonder if that has something to do with it. You can see here where the error is being thrown:

https://github.com/weareferal/craft-remote-sync/blob/62066a18638f3c85416e217d3f2a2ed29fcaf1dd/src/services/providers/S3Provider.php#L189

The full exeption from AWS should be in the logs and provide a bit more detail

**Comment by timmyomahony** [comment]
Any luck debugging the issue further @indrek-k ?

**Comment by indrek-k** [comment]
Thanks! This is my first time with Craft, so I didn't even realize I should check the logs. It turned out to be a cURL SSL error.
