### ISSUE TITLE
Support for MinIO (or custom s3 compatible endpoints)

### ISSUE THREAD

**Issue by FlomoN** [weareferal/craft-remote-sync#31]
Hi,

I'm looking to use this with a self-hosted instance of MinIO (which is 100% compatible with Amazon S3), which in result has a custom endpoint URL (Like it was initially requested by #19 ).

Would be nice if either custom endpoint support or an additional provider could be added. However, I think a custom endpoint would be the best option for general applicability.

[From MinIO webpage](https://min.io/)
> Amazon’s S3 API is the defacto standard in the object storage world. MinIO is the defacto standard for S3 compatibility and was one of the first to adopt the API and the first to add support for S3 Select. More than 750 organizations, including Microsoft Azure, use MinIO’s S3 Gateway - more than the rest of the industry combined.

**Comment by timmyomahony** [comment]
Hi @FlomoN that's a good suggestion. I should probably add a "generic S3" backend that can be used with any service that supports the S3 API

**Comment by FlomoN** [comment]
That would be great :)

**Comment by timmyomahony** [comment]
Added in 1.4.0 https://github.com/weareferal/craft-remote-sync/commit/1f2f7bd00e6b01a99b02c2fba4da673dfed8258d. You can now use a generic S3 backend and specify the endpoint
