### ISSUE TITLE
Error with 1.3.4 update

### ISSUE THREAD

**Issue by TUSAB-web** [weareferal/craft-remote-sync#36]
I attempted to update Remote Sync when it appeared in my Craft CP. I got the following error message:

-----
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Installation request for weareferal/remote-sync 1.3.4 -> satisfiable by weareferal/remote-sync[1.3.4].
- weareferal/remote-sync 1.3.4 requires weareferal/remote-core ^1.1.5 -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
see for more details.
- It's a private package and you forgot to add a custom repository to find it

Read for further common problems.
Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.

**Comment by timmyomahony** [comment]
That's strange. The Sync package uses another separate library as a dependency (`remote-core`) and it's saying that version `1.1.5` of the core package isn't available, but it is https://packagist.org/packages/weareferal/remote-core

I just tried updating a site of mine via the control panel, and it went OK. I wonder was it a temporary glitch - have you tried a second time to perform the update?

**Comment by TUSAB-web** [comment]
I discarded all changes on git so I was rolled back to 1.3.2 and it appeared ok. Then I re-applied the update, and it went through. However, now when I try to open the settings of the plugin I get:

Copy Stacktrace Search Stackoverflow Search Google Exception
Invalid Configuration – yii\base\InvalidConfigException

Failed to instantiate component or class "weareferal\remotecore\assets\remotecoresettings\RemoteCoreSettingsAsset".
↵
Caused by: ReflectionException

Class weareferal\remotecore\assets\remotecoresettings\RemoteCoreSettingsAsset does not exist

in /var/www/html/vendor/yiisoft/yii2/di/Container.php at line 453

**Comment by timmyomahony** [comment]
Ah. I think there might be a bug in 1.3.4 so. That path should be:

```
weareferal\remotecore\assets\RemoteCoreSettings\RemoteCoreSettingsAsset
```

I've just pushed an updated 1.3.5 version that should hopefully fix the issue

**Comment by TUSAB-web** [comment]
I just downloaded and installed the update. Just tested and everything is working normally. Thanks for the prompt reply and quick fix!

**Comment by timmyomahony** [comment]
👍 Glad it's working. Let me know if you have any other issues
