### ISSUE TITLE
Timeout setting 300?

### ISSUE THREAD

**Issue by chadcrowell** [weareferal/craft-remote-sync#38]
On my local, I have php's script timeout set to 600. However, when pulling/restoring a db with Remote Sync, it times out showing that it has surpassed 300. Is there some setting within the plugin that sets the timeout at 300? If so, could you make that a config setting so I can increase it in environments that need it?

https://d.pr/i/dxBj9K
https://d.pr/i/Rz5ZUp

**Comment by timmyomahony** [comment]
Ah interesting, this looks like a queue issue:

- https://github.com/craftcms/cms/issues/3147
- https://craftcms.stackexchange.com/questions/25437/queue-exec-time

It looks like this can either be fixed on "my end" by adding a config variable that the queue uses when pushing jobs, or on "your end" by adding a config variable to the project for _all_ queue calls. 

I'll add an issue for this and look to add a config variable on my end.

**Comment by timmyomahony** [comment]
I've added ability to use a different TTR in the queue in 1.4.0. Alternatively using the CLI should avoid this problem. https://github.com/weareferal/craft-remote-sync/commit/1f2f7bd00e6b01a99b02c2fba4da673dfed8258d
