### ISSUE TITLE
Asset restore doesn’t pull images

### ISSUE THREAD

**Issue by TUSAB-web** [weareferal/craft-remote-sync#40]
On the staging server, I did a push of my assets. On my local environment, I did a pull. This took a couple minutes (about 300MB), and when it was done it said “volumes pulled." I looked in my local assets folder and no files had been downloaded there. I searched my hard drive and they weren’t anywhere. There are entries in the assets section for the images, but they are broken links and the file cannot be found. I moved all files out of my local assets folder and cleared caches and tried again... it once again said “volumes pulled” but there was just an empty assets folder at the end of the process.

The database sync seems to be working fine though.

**Comment by timmyomahony** [comment]
Strange. Are you just using a local volume (as opposed to an S3 volume or Digital Ocean or something else like that)? That's strange that they are not appearing. What sync backend are you using (S3, B2 etc.)?

**Comment by TUSAB-web** [comment]
I am using a local volume on the staging and on my local dev. Using B2 for sync. It doesn’t seem to be returning an error; it says it completed the task. My local dev is using docker - I have a coworker having the same issue with the same docker setup I have. I checked permissions on the local asset folder and they are set correctly (I can easily add/remove assets with the Craft CP).

Matthew

On Dec 23, 2020, at 06:52, timmyomahony <notifications@github.com> wrote:



Strange. Are you just using a local volume (as opposed to an S3 volume or Digital Ocean or something else like that)? That's strange that they are not appearing. What sync backend are you using (S3, B2 etc.)?

**Comment by timmyomahony** [comment]
Hi @TUSAB-web I dropped the ball on this issue so apologies 😬. It has been a challenge to manage the plugins alongside client work (not an excuse, just an explanation). I'm getting back on top of everything and have a recent Craft 4 update. Let me know if you stuck with the plugin. If not, I'd be happy to sort you out with a free license if you want to try it out again on a project.

I'm going to close this issue for the moment, but happy to investigate and test out if you think it's not been sorted in the latest version.
