### ISSUE TITLE
Cannot push database (Craft 3.7)

### ISSUE THREAD

**Issue by TUSAB-web** [weareferal/craft-remote-sync#42]
In Craft 3.7.0, I get an error when pushing the database to Backblaze. Here’s what I saw in the log:

`2021-07-19 11:58:53 [-][1][-][error][Aws\S3\Exception\S3MultipartUploadException] Aws\S3\Exception\S3MultipartUploadException: An exception occurred while uploading parts to a multipart upload. The following parts had errors:
- Part 4: Error executing "UploadPart" on “URL REMOVED"; AWS HTTP error: cURL error 7: Failed to connect to s3.us-west-002.backblazeb2.com port 443: Connection timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for URL REMOVED
 in /home/site/vendor/aws/aws-sdk-php/src/Multipart/AbstractUploadManager.php:134
`

This worked fine on the version of Craft just prior to 3.7.0

**Comment by TUSAB-web** [comment]
Updated to Craft 3.7.3.2 - pushing DB is working correctly now.

**Comment by timmyomahony** [comment]
Thanks for reporting @TUSAB-web, I'll check it out on 3.7.0
