### ISSUE TITLE
Craft 4

### ISSUE THREAD

**Issue by josh-attwood** [weareferal/craft-remote-sync#46]
Have found your plugin extremely useful over the last year for syncing between local, staging & prod.

Do you have any idea of when you guys might support Craft 4?

**Comment by TUSAB-web** [comment]
Just wanted to bump this. I have been using the plugin and would like to continue with Craft 4, but perhaps this is being abandoned?

**Comment by timmyomahony** [comment]
Apologies. No not abandoned. Finally able to catch up on this plugin after a long hiatus so will be updating as soon as I can.

**Comment by TUSAB-web** [comment]
That’s great news! I haven’t moved to Craft 4 yet. Just planning the move and figuring out which plugins might (or might not) be available going forward. Thanks for the reply.

**Comment by timmyomahony** [comment]
Just an update that I am still working on this and haven't forgotten. Taking longer than expected due to updates to the volumes with filesystems in Craft 4.

**Comment by MattAppleton** [comment]
Thanks for the update Timmy, much appreciated…



Matt

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Modern Activity, Buzzer #3, 19 Warburton Road, London E8 3RT 
M: +44 (0)7941 806 766
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by josh-attwood** [comment]
Hi @timmyomahony, just checking in on how progress for this is going? 

If the new asset structure is a problem would it possible to release a database only version, we tend to keep all our assets on AWS so syncing the assets isn't really a priority for us. Or perhaps we can just install the craft 3 version via composer, would that work?

**Comment by timmyomahony** [comment]
Sorry @josh-attwood, I promise support for 4 is on the way 🥲 I had made a push to get it out-the-door but as you alluded to, there's been changes with the filesystem and assets in Craft 4 that put a spanner in the works. Disabling assets backup temporarily might be a good stop-gap to get it out the door. Either way, I'm going to get stuck back in next week to finally get a release out. Thanks for the patience 😬

**Comment by timmyomahony** [comment]
OK, I was able to sort out the issues with the filesystem changes, so 4.0.0 should finally be here. You can see the release:

https://github.com/weareferal/craft-remote-sync/releases/tag/4.0.0

Check it out and let me know how you get on.
