### ISSUE TITLE
Plugin breaking the users section in the admin

### ISSUE THREAD

**Issue by josh-attwood** [weareferal/craft-remote-sync#48]
Really glad this has now been moved into craft 4! Thank you!

Quite a major issue at the minute which is making the plugin unusable.

When you go to edit user permissions in the admin, either through settings->users -> groups or through an individual's user settings, if not in devMode you get a server error and when in devMode you get:

`Key "heading" for array with keys "remotesync" does not exist.`

This is also a problem for for remote backups plugin. 

Most probably just a template issue with Craft 4.

**Comment by timmyomahony** [comment]
Thanks @josh-attwood looks like I missed that permissions have slightly changed:

https://craftcms.com/docs/4.x/extend/updating-plugins.html#user-permissions

I'll fix that today. Thanks for reporting.

**Comment by timmyomahony** [comment]
OK, should be fixed in v4.0.1 https://github.com/weareferal/craft-remote-sync/releases/tag/4.0.1
