### ISSUE TITLE
Environment not added to DB name in DO Spaces in version 4.1.1

### ISSUE THREAD

**Issue by jan-thoma** [weareferal/craft-remote-sync#54]
When using this Plugin the environment craft is running in is not added to the DB Backup file name.  The Plugin then refuses to list the database backups. I'm running this on DO Spaces. This happend with the upgrade to 4.1.1

![Bildschirm­foto 2022-11-09 um 10 33 50](https://user-images.githubusercontent.com/24450307/200794210-6bce5d73-2287-45e9-b11d-de096daa2716.png)

**Comment by timmyomahony** [comment]
Hi @jan-thoma thanks for the report, I'll look into this. 

For my own info, here's where the env is getting generated:

https://github.com/weareferal/craft-remote-core/blob/main/src/services/ProviderService.php#L456

**Comment by timmyomahony** [comment]
@jan-thoma do you have `CRAFT_ENVIRONMENT` set in your `.env`?

**Comment by jan-thoma** [comment]
I had `ENVIRONMENT` set. Changed it to `CRAFT_ENVIRONMENT` no it works as it should

**Comment by timmyomahony** [comment]
OK great. I think I might still add a small fix to use a `default` value when no environment is detected, so going to leave this open for a little while.

**Comment by timmyomahony** [comment]
A default "unknown" environment will now be added to the filename in `craft-remote-core` `v4.1.1` which should avoid issues like this in the future.
