### ISSUE TITLE
Can't see my teammates databases and/or assets

### ISSUE THREAD

**Issue by daafbleumink** [weareferal/craft-remote-sync#57]
Hi there,

I want to use your remote sync plug-in when collaborating on a project with my colleague.

In my Digital Ocean Space I see all of the back-ups that we create, but in Craft we can't see each other's back-ups.

Any pointers as to why this is happening?

Love the plugin btw!

Cheers,

Daaf

**Comment by timmyomahony** [comment]
Hi Daaf, that's strange - I assume you are both running the same codebase and using the same Digital Ocean credentials when configuring the plugin (as well as backing up files to the exact same location on the Digital Ocean space)?

**Comment by daafbleumink** [comment]
> Hi Daaf, that's strange - I assume you are both running the same codebase and using the same Digital Ocean credentials when configuring the plugin (as well as backing up files to the exact same location on the Digital Ocean space)?

Oops, resolved. My bad! There was one setting off 🤦‍♂️

**Comment by timmyomahony** [comment]
No worries, glad you got it sorted
