### ISSUE TITLE
Incorrect reference in docs to config file

### ISSUE THREAD

**Issue by chadcrowell** [weareferal/craft-remote-sync#8]
> Alternatively, if you want to configure the plugin on a per-environment basis, you can copy the config/remote-backup.example.php to your project's config/remote-backup.php file. These settings will override the Control Panel settings.

This repo is the Remote Sync repo, the text above references a file for `remote-backup.php`. Also, the example config file in the repo is named `remote-backup.example.php`, I think it should be `remote-sync.example.php`.

**Comment by timmyomahony** [comment]
Well spotted thanks, that's fixed now
